// 20231020102915
// https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/geonames-all-cities-with-a-population-1000/records?limit=20

export const _cities = [
  {
    geoname_id: '10364493',
    name: 'Khaddamari',
    ascii_name: 'Khaddamari',
    alternate_names: null,
    feature_class: 'P',
    feature_code: 'PPLA2',
    country_code: 'NG',
    cou_name_en: 'Nigeria',
    country_code_2: null,
    admin1_code: '27',
    admin2_code: '113',
    admin3_code: '11308',
    admin4_code: null,
    population: 0,
    elevation: null,
    dem: 311,
    timezone: 'Africa/Lagos',
    modification_date: '2016-06-22',
    label_en: 'Nigeria',
    coordinates: {
      lon: 13.23062,
      lat: 11.92589,
    },
  },
  {
    geoname_id: '3615683',
    name: 'Wiwilí',
    ascii_name: 'Wiwili',
    alternate_names: [
      'Gueigueili',
      'Guiguili',
      'Guiguilí',
      'Guiquili',
      'Güigüilí',
      'Wiwili',
      'Wiwili de Nueva Segovia',
      'Wiwilí',
      'Wiwilí de Nueva Segovia',
    ],
    feature_class: 'P',
    feature_code: 'PPLA2',
    country_code: 'NI',
    cou_name_en: 'Nicaragua',
    country_code_2: null,
    admin1_code: '13',
    admin2_code: '0560',
    admin3_code: null,
    admin4_code: null,
    population: 6955,
    elevation: null,
    dem: 313,
    timezone: 'America/Managua',
    modification_date: '2020-06-10',
    label_en: 'Nicaragua',
    coordinates: {
      lon: -85.8254,
      lat: 13.62679,
    },
  },
  {
    geoname_id: '3616311',
    name: 'Sébaco',
    ascii_name: 'Sebaco',
    alternate_names: ['Sebaco', 'Sébaco'],
    feature_class: 'P',
    feature_code: 'PPLA2',
    country_code: 'NI',
    cou_name_en: 'Nicaragua',
    country_code_2: null,
    admin1_code: '12',
    admin2_code: null,
    admin3_code: null,
    admin4_code: null,
    population: 0,
    elevation: null,
    dem: 475,
    timezone: 'America/Managua',
    modification_date: '2018-08-08',
    label_en: 'Nicaragua',
    coordinates: {
      lon: -86.0963,
      lat: 12.85321,
    },
  },
  {
    geoname_id: '3616356',
    name: 'Santo Domingo',
    ascii_name: 'Santo Domingo',
    alternate_names: ['Santa Domingo', 'Santo Domingo'],
    feature_class: 'P',
    feature_code: 'PPLA2',
    country_code: 'NI',
    cou_name_en: 'Nicaragua',
    country_code_2: null,
    admin1_code: '04',
    admin2_code: null,
    admin3_code: null,
    admin4_code: null,
    population: 5827,
    elevation: null,
    dem: 509,
    timezone: 'America/Managua',
    modification_date: '2018-08-08',
    label_en: 'Nicaragua',
    coordinates: {
      lon: -85.08235,
      lat: 12.26438,
    },
  },
  {
    geoname_id: '3616732',
    name: 'San Juan de Limay',
    ascii_name: 'San Juan de Limay',
    alternate_names: ['Limay', 'San Juan de Limay'],
    feature_class: 'P',
    feature_code: 'PPLA2',
    country_code: 'NI',
    cou_name_en: 'Nicaragua',
    country_code_2: null,
    admin1_code: '05',
    admin2_code: null,
    admin3_code: null,
    admin4_code: null,
    population: 4997,
    elevation: null,
    dem: 284,
    timezone: 'America/Managua',
    modification_date: '2018-08-08',
    label_en: 'Nicaragua',
    coordinates: {
      lon: -86.61234,
      lat: 13.17603,
    },
  },
  {
    geoname_id: '3620170',
    name: 'Diriamba',
    ascii_name: 'Diriamba',
    alternate_names: ['Diriamba', 'Diriambo'],
    feature_class: 'P',
    feature_code: 'PPLA2',
    country_code: 'NI',
    cou_name_en: 'Nicaragua',
    country_code_2: null,
    admin1_code: '02',
    admin2_code: null,
    admin3_code: null,
    admin4_code: null,
    population: 35008,
    elevation: null,
    dem: 583,
    timezone: 'America/Managua',
    modification_date: '2018-08-08',
    label_en: 'Nicaragua',
    coordinates: {
      lon: -86.23922,
      lat: 11.85812,
    },
  },
  {
    geoname_id: '3620269',
    name: 'Corinto',
    ascii_name: 'Corinto',
    alternate_names: ['Corinto'],
    feature_class: 'P',
    feature_code: 'PPLA2',
    country_code: 'NI',
    cou_name_en: 'Nicaragua',
    country_code_2: null,
    admin1_code: '03',
    admin2_code: null,
    admin3_code: null,
    admin4_code: null,
    population: 19183,
    elevation: null,
    dem: 9,
    timezone: 'America/Managua',
    modification_date: '2018-08-08',
    label_en: 'Nicaragua',
    coordinates: {
      lon: -87.17304,
      lat: 12.4825,
    },
  },
  {
    geoname_id: '3620318',
    name: 'Comalapa',
    ascii_name: 'Comalapa',
    alternate_names: ['Comalapa'],
    feature_class: 'P',
    feature_code: 'PPLA2',
    country_code: 'NI',
    cou_name_en: 'Nicaragua',
    country_code_2: null,
    admin1_code: '04',
    admin2_code: null,
    admin3_code: null,
    admin4_code: null,
    population: 1272,
    elevation: null,
    dem: 273,
    timezone: 'America/Managua',
    modification_date: '2018-08-08',
    label_en: 'Nicaragua',
    coordinates: {
      lon: -85.51081,
      lat: 12.28345,
    },
  },
  {
    geoname_id: '3620353',
    name: 'Ciudad Antigua',
    ascii_name: 'Ciudad Antigua',
    alternate_names: ['Ciudad Antigua'],
    feature_class: 'P',
    feature_code: 'PPLA2',
    country_code: 'NI',
    cou_name_en: 'Nicaragua',
    country_code_2: null,
    admin1_code: '13',
    admin2_code: null,
    admin3_code: null,
    admin4_code: null,
    population: 1787,
    elevation: null,
    dem: 634,
    timezone: 'America/Managua',
    modification_date: '2018-08-08',
    label_en: 'Nicaragua',
    coordinates: {
      lon: -86.30815,
      lat: 13.6406,
    },
  },
  {
    geoname_id: '3620674',
    name: 'Boaco',
    ascii_name: 'Boaco',
    alternate_names: ['Boaco'],
    feature_class: 'P',
    feature_code: 'PPLA',
    country_code: 'NI',
    cou_name_en: 'Nicaragua',
    country_code_2: null,
    admin1_code: '01',
    admin2_code: null,
    admin3_code: null,
    admin4_code: null,
    population: 29046,
    elevation: null,
    dem: 380,
    timezone: 'America/Managua',
    modification_date: '2013-06-28',
    label_en: 'Nicaragua',
    coordinates: {
      lon: -85.6586,
      lat: 12.47224,
    },
  },
  {
    geoname_id: '2743590',
    name: 'De Westereen',
    ascii_name: 'De Westereen',
    alternate_names: ['De Westereen', 'De Westerein', 'Zwaagwesteinde'],
    feature_class: 'P',
    feature_code: 'PPL',
    country_code: 'NL',
    cou_name_en: 'Netherlands',
    country_code_2: null,
    admin1_code: '02',
    admin2_code: '1891',
    admin3_code: null,
    admin4_code: null,
    population: 5030,
    elevation: null,
    dem: 2,
    timezone: 'Europe/Amsterdam',
    modification_date: '2019-07-23',
    label_en: 'Netherlands',
    coordinates: {
      lon: 6.0363,
      lat: 53.25731,
    },
  },
  {
    geoname_id: '2743807',
    name: 'Zuid-Beijerland',
    ascii_name: 'Zuid-Beijerland',
    alternate_names: ['Zuidbeierland'],
    feature_class: 'P',
    feature_code: 'PPL',
    country_code: 'NL',
    cou_name_en: 'Netherlands',
    country_code_2: null,
    admin1_code: '11',
    admin2_code: '1963',
    admin3_code: null,
    admin4_code: null,
    population: 2740,
    elevation: null,
    dem: 0,
    timezone: 'Europe/Amsterdam',
    modification_date: '2019-01-30',
    label_en: 'Netherlands',
    coordinates: {
      lon: 4.36806,
      lat: 51.75083,
    },
  },
  {
    geoname_id: '2744129',
    name: 'Yerseke',
    ascii_name: 'Yerseke',
    alternate_names: [
      'Erseke',
      'IJerseka',
      'Iersake',
      'Ierseke',
      'Iese',
      'Yrseke',
      'Ерсеке',
      'یرسکے',
    ],
    feature_class: 'P',
    feature_code: 'PPL',
    country_code: 'NL',
    cou_name_en: 'Netherlands',
    country_code_2: null,
    admin1_code: '10',
    admin2_code: '0703',
    admin3_code: null,
    admin4_code: null,
    population: 6541,
    elevation: null,
    dem: 4,
    timezone: 'Europe/Amsterdam',
    modification_date: '2017-10-17',
    label_en: 'Netherlands',
    coordinates: {
      lon: 4.05,
      lat: 51.4925,
    },
  },
  {
    geoname_id: '2744344',
    name: 'Winschoten',
    ascii_name: 'Winschoten',
    alternate_names: [
      'Vinskhoten',
      'Winschoten',
      'Wynskoat',
      'wen si huo teng',
      'Винсхотен',
      '溫斯霍滕',
    ],
    feature_class: 'P',
    feature_code: 'PPL',
    country_code: 'NL',
    cou_name_en: 'Netherlands',
    country_code_2: null,
    admin1_code: '04',
    admin2_code: '1895',
    admin3_code: null,
    admin4_code: null,
    population: 18506,
    elevation: null,
    dem: 3,
    timezone: 'Europe/Amsterdam',
    modification_date: '2017-10-17',
    label_en: 'Netherlands',
    coordinates: {
      lon: 7.03472,
      lat: 53.14417,
    },
  },
  {
    geoname_id: '2744514',
    name: 'Wijchen',
    ascii_name: 'Wijchen',
    alternate_names: ['Vijchen', 'Wijchen', 'Вийчен'],
    feature_class: 'P',
    feature_code: 'PPL',
    country_code: 'NL',
    cou_name_en: 'Netherlands',
    country_code_2: null,
    admin1_code: '03',
    admin2_code: '0296',
    admin3_code: null,
    admin4_code: null,
    population: 32693,
    elevation: null,
    dem: 10,
    timezone: 'Europe/Amsterdam',
    modification_date: '2017-10-17',
    label_en: 'Netherlands',
    coordinates: {
      lon: 5.725,
      lat: 51.80917,
    },
  },
  {
    geoname_id: '2744534',
    name: 'Wieringerwaard',
    ascii_name: 'Wieringerwaard',
    alternate_names: null,
    feature_class: 'P',
    feature_code: 'PPL',
    country_code: 'NL',
    cou_name_en: 'Netherlands',
    country_code_2: null,
    admin1_code: '07',
    admin2_code: '1911',
    admin3_code: null,
    admin4_code: null,
    population: 1795,
    elevation: null,
    dem: -1,
    timezone: 'Europe/Amsterdam',
    modification_date: '2017-10-17',
    label_en: 'Netherlands',
    coordinates: {
      lon: 4.86528,
      lat: 52.83583,
    },
  },
  {
    geoname_id: '2744885',
    name: 'Weijpoort',
    ascii_name: 'Weijpoort',
    alternate_names: null,
    feature_class: 'P',
    feature_code: 'PPL',
    country_code: 'NL',
    cou_name_en: 'Netherlands',
    country_code_2: null,
    admin1_code: '11',
    admin2_code: '1901',
    admin3_code: null,
    admin4_code: null,
    population: 1370,
    elevation: null,
    dem: -1,
    timezone: 'Europe/Amsterdam',
    modification_date: '2017-03-24',
    label_en: 'Netherlands',
    coordinates: {
      lon: 4.80278,
      lat: 52.08167,
    },
  },
  {
    geoname_id: '2744919',
    name: 'Weerestein',
    ascii_name: 'Weerestein',
    alternate_names: null,
    feature_class: 'P',
    feature_code: 'PPL',
    country_code: 'NL',
    cou_name_en: 'Netherlands',
    country_code_2: null,
    admin1_code: '11',
    admin2_code: '0534',
    admin3_code: null,
    admin4_code: null,
    population: 1105,
    elevation: null,
    dem: 0,
    timezone: 'Europe/Amsterdam',
    modification_date: '2017-03-24',
    label_en: 'Netherlands',
    coordinates: {
      lon: 4.58861,
      lat: 52.30381,
    },
  },
  {
    geoname_id: '2745003',
    name: 'Warnsveld',
    ascii_name: 'Warnsveld',
    alternate_names: null,
    feature_class: 'P',
    feature_code: 'PPL',
    country_code: 'NL',
    cou_name_en: 'Netherlands',
    country_code_2: null,
    admin1_code: '03',
    admin2_code: '0301',
    admin3_code: null,
    admin4_code: null,
    population: 9200,
    elevation: null,
    dem: 10,
    timezone: 'Europe/Amsterdam',
    modification_date: '2017-10-17',
    label_en: 'Netherlands',
    coordinates: {
      lon: 6.23056,
      lat: 52.1375,
    },
  },
  {
    geoname_id: '2745091',
    name: 'Wagenberg',
    ascii_name: 'Wagenberg',
    alternate_names: null,
    feature_class: 'P',
    feature_code: 'PPL',
    country_code: 'NL',
    cou_name_en: 'Netherlands',
    country_code_2: null,
    admin1_code: '06',
    admin2_code: '1719',
    admin3_code: null,
    admin4_code: null,
    population: 1905,
    elevation: null,
    dem: 4,
    timezone: 'Europe/Amsterdam',
    modification_date: '2017-10-17',
    label_en: 'Netherlands',
    coordinates: {
      lon: 4.74861,
      lat: 51.665,
    },
  },
];
